stages:
  - unit_test
  - build
  - test_server
  - integration_tests
  - deploy_production
  
variables:
  REGISTRY: gcr.io/${CI_PROJECT_PATH}

test:
  stage: unit_test
  image: golang:latest
  script:
    - go test -i

docker:build:
  stage: build
  image: docker:latest
  script:
    - docker build -t $REGISTRY:${CI_COMMIT_SHA} .
    - docker push $REGISTRY:${CI_COMMIT_SHA}

deploy:test_server:
  stage: test_server
  image: kiwigrid/gcloud-kubectl-helm:3.2.1-289.0.0-250
  script:
    - helm upgrade --create-namespace --wait -i --set image.tag=${CI_COMMIT_SHA} -n demo-app demo-app .helm

test:test_server:
  stage: integration_tests
  image: golang:latest
  script:
    - echo "Running integration tests"
    
deploy:production:
  stage: deploy_production
  image: kiwigrid/gcloud-kubectl-helm:3.2.1-289.0.0-250
  when: manual
  script:
    - helm upgrade --create-namespace --wait -i --set image.tag=${CI_COMMIT_SHA} -n demo-app demo-app .helm    
