stages:
  - build
  - test
  - publish
  - deploy
  
variables:
  REGISTRY: gcr.io/${CI_PROJECT_PATH}

docker:build:
  stage: build
  image: docker:latest
  before_script:
    - docker pull $REGISTRY:builder || true
  script:
    - docker build --target builder --cache-from=$REGISTRY:builder -t $REGISTRY:builder .
    - docker build --target runtime-image --cache-from=$REGISTRY:builder -t $REGISTRY:${CI_COMMIT_SHA} .
    - docker push $REGISTRY:builder
    - docker push $REGISTRY:${CI_COMMIT_SHA}

test:
  stage: test
  image: docker:latest
  needs: ["docker:build"]
  before_script:
    - docker pull $REGISTRY:builder || true 
  script:
    - docker run -it $REGISTRY:builder go test -i
    
publish:latest:
  stage: publish
  before_script:
    - docker pull $REGISTRY:${CI_COMMIT_SHA}
  script:
    - docker tag $REGISTRY:${CI_COMMIT_SHA} $REGISTRY:latest
    - docker push $REGISTRY:latest
    
deploy:
  image: kiwigrid/gcloud-kubectl-helm:3.2.1-289.0.0-250
  only:
  script:
    - helm upgrade --create-namespace --wait -i --set image.tag=${CI_COMMIT_SHA} -n demo-app demo-app .helm
